# -------------------------------- ur5e parameters --------------------------------
ur5e:
 dh:
  a1: 0.0
  a2: -0.425
  a3: -0.3922
  a4: 0.0
  a5: 0.0
  a6: 0.0

  d1: 0.1625
  d2: 0.0
  d3: 0.0
  d4: 0.1333
  d5: 0.0997
  d6: 0.0996

  alpha1: 1.5707963267948966
  alpha2: 0.0
  alpha3: 0.0
  alpha4: 1.5707963267948966
  alpha5: -1.5707963267948966
  alpha6: 0.0


 inertia:
  m1: 3.761
  m2: 8.058
  m3: 2.846
  m4: 1.37
  m5: 1.3
  m6: 0.365

  I1: [0.0, 0.0, 0.0]
  I2: [0.0, 0.0, 0.0]
  I3: [0.0, 0.0, 0.0]
  I4: [0.0, 0.0, 0.0]
  I5: [0.0, 0.0, 0.0]
  I6: [0.0, 0.0, 0.0]

  Pc1: [0.0, -0.00193, -0.02561]
  Pc2: [-0.2125, 0.0, -0.0199]
  Pc3: [-0.2422, 0.0, 0.0265]
  Pc4: [0.0, -0.01634, -0.0018]
  Pc5: [0.0, 0.01634, -0.0018]
  Pc6: [0.0, 0.0, -0.001159]




# -------------------------------- ur5 parameters --------------------------------
ur5:
 dh:
  a1: 0.0
  a2: -0.425
  a3: -0.39225
  a4: 0.0
  a5: 0.0
  a6: 0.0

  d1: 0.089159
  d2: 0.0
  d3: 0.0
  d4: 0.10915
  d5: 0.09465
  d6: 0.0823

  alpha1: 1.5707963267948966
  alpha2: 0.0
  alpha3: 0.0
  alpha4: 1.5707963267948966
  alpha5: -1.5707963267948966
  alpha6: 0.0


 inertia:
  m1: 3.7
  m2: 8.393
  m3: 2.33
  m4: 1.219
  m5: 1.219
  m6: 0.1879

  I1: [0.0, 0.0, 0.0]
  I2: [0.0, 0.0, 0.0]
  I3: [0.0, 0.0, 0.0]
  I4: [0.0, 0.0, 0.0]
  I5: [0.0, 0.0, 0.0]
  I6: [0.0, 0.0, 0.0]

  Pc1: [0.0, -0.00193, -0.02561]
  Pc2: [-0.2125, 0.0, -0.0199]
  Pc3: [-0.2422, 0.0, 0.0265]
  Pc4: [0.0, -0.01634, -0.0018]
  Pc5: [0.0, 0.01634, -0.0018]
  Pc6: [0.0, 0.0, -0.001159]